// Main application class, generated by Spring Initializr.
// Must live in the top package so that @SpringBootApplication annotation
// can find all the components.

package com.example.welcome;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import com.example.welcome.model.*;
import com.example.welcome.service.*;
// import org.slf4j.Logger;
// import org.slf4j.LoggerFactory;

@SpringBootApplication
// @ComponentScan(basePackages = {"com.example.welcome.service"})
public class ClientApplication {

    // private static final Logger log = LoggerFactory.getLogger(ClientApplication.class);
    public static void main(String[] args) {
        SpringApplication.run(ClientApplication.class, args);
}

    // The initDB() @Bean is run automatically on startup, before the
    // @RestController is started.
    // The body could access command line argument args (but doesn't).
    // The fact that initDB() requires a WelcomeService argument tells Spring
    // to auto-configure and pass EventService, InterestService and UserService instances, which initDB()
    // amends by adding more events instances.
    @Bean
        public CommandLineRunner initDB(EventService es, InterestService is, UserService us){
        return (args) -> {

            Event event1 =new Event("A wonderful description", "In a wonderful place", "21 October 2022", "8:32am", 30, 5);
            // User user1 = new User("qwerty123", "Alex");
            // event1.addAttendee(user1);
            // Interest interest1 = new Interest("AI");
            // user1.addInterest(interest1);
            // is.addInterest(interest1);
            // us.addUser(user1);
            es.addEvent(event1);

            Event event2 = new Event("A great description", "In a great place", "3 May 2022", "01:00pm", 60, 2);
            // event2.addAttendee(user1);
            es.addEvent(event2);
            

            Event event3 = new Event("Intelligence through the Ages", "Wallace Monument", "1 April 2025", "9am", 45, 1234);
            // event3.addAttendee(user1);
            es.addEvent(event3);

            // Interest interest2 = new Interest("Not AI");
            // is.addInterest(interest2);
            // user1.removeAllInterests();
            // user1.addInterest(interest2);
            // us.addUser(user1);

        };
    }  
}

